// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsdsbsnnygtdjiwwumml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzZHNic25ueWd0ZGppd3d1bW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTg1MTgsImV4cCI6MjA2NzI5NDUxOH0.5wMjiGOW-ih70pBYAUF_kiaBzhgQVFl-ejbJObv3eJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});